Update README.md and example models.
openbrewerydb/fastapi-beta pull request #17
Opened 2023-01-08 23:13 UTC by milsman2

- Demo model of breweries.
- Demo schema of breweries.

2023-01-09 02:09 UTC, chrisjm requested changes
Thanks for pushing this forward @milsman2 ! Couple of comments and update requests. 

As always, feel free to question and/or push-back. 🙂🍻

2023-01-09 02:09 UTC, chrisjm commented on README.md
> +- Change the host to any connection
Let's nest these under "Run the server" for clarity. 

Also, feel free to completely reorg this section. I just kind of made it on the fly.

2023-01-09 02:09 UTC, chrisjm commented on schemas/__init__.py
> +from app.schemas.breweries import  Brewery, BreweryCreate, BreweryUpdate, BreweryUpdateRestricted
Only `Brewery` is necessary. We're going to keep the API read-only for now.

2023-01-09 02:09 UTC, chrisjm commented on models/brewery.py
> +    latitude = Column(Float)
Let's also add `created_at` and `updated_at` columns. Datetime, whatever that is in Python :)

2023-01-09 02:09 UTC, chrisjm commented on schemas/breweries.py
> +    latitude: int | None
Same `created_at` and `updated_at`

2023-01-09 02:09 UTC, chrisjm commented on schemas/breweries.py
> +    ...
Currently, it's a read-only API, so some of these classes aren't necessary. 

Not sure about the `BreweryInDB` classes. We don't store contributors in the DB yet but should be built in for v2.

2023-01-09 02:53 UTC, chrisjm commented
Also, do you know if there are any tests we can add to this?

2023-01-10 04:01 UTC, chrisjm approved these changes

2023-01-10 04:01 UTC, milsman2 commented
There are definitely ways to test but I haven't gotten into that part of FastAPI too deep yet. Definitely can do soon down the road once we have an MVP.

2023-01-10 04:01 UTC, merged