Breweries endpoint placeholder.
openbrewerydb/fastapi-beta pull request #22
Opened 2023-01-15 18:31 UTC by milsman2

Set up the breweries endpoint with a basic placeholder.

2023-01-17 02:13 UTC, chrisjm requested changes
Awesome! Thank you, @milsman2! 

Let's also add a test for the `/v1/breweries` endpoint, even though it's still a placeholder. That way it helps to remind us to keep updating the test once we fill it in.

2023-01-18 04:13 UTC, milsman2 reviewed
Looks good to me.

2023-01-18 04:31 UTC, chrisjm approved these changes

2023-01-18 04:32 UTC, chrisjm commented
🍻 !

2023-01-18 23:50 UTC, merged